crashes/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('<slug:org_slug>/', views.org, name='org'),
    path('<slug:org_slug>/<slug:project_slug>/', views.project, name='project'),
    path('<slug:org_slug>/<slug:project_slug>/package/<str:package_name>/', views.package, name='package')
]

facs/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('crashes/', include('crashes.urls'))
]

crashes/models.py
from django.db import models
import functools

class Organization(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField()

    def __str__(self):
        return self.name

class Project(models.Model):
    org = models.ForeignKey(Organization, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=255)
    slug = models.SlugField(null=True, blank=True)
    events_endpoint = models.CharField(max_length=1024)
    token = models.TextField()

    def __str__(self):
        return self.name

class Category(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)

    class Meta:
        unique_together = ['project', 'name']
        ordering = ['name']

    def __str__(self):
        return "%s (id=%s)" % (self.name, self.id)

    def group_count(self):
        return self.eventgroup_set.all().count()

    # todo ugh, these should be sql instead

    def event_count(self):
        return functools.reduce(lambda sum, eg: sum + eg.event_count(), self.eventgroup_set.all(), 0)

    def event_info_count(self):
        return functools.reduce(lambda sum, eg: sum + eg.event_info_count(), self.eventgroup_set.all(), 0)

    def event_fatal_count(self):
        return functools.reduce(lambda sum, eg: sum + eg.event_fatal_count(), self.eventgroup_set.all(), 0)

class CategoryCount(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    keyed_tag = models.ForeignKey("EventTagKeyed", null=True, blank=True, on_delete=models.SET_NULL)
    date = models.DateField()
    info_count = models.IntegerField()
    fatal_count = models.IntegerField()

    class Meta:
        unique_together = ['keyed_tag', 'category', 'date']

    def __str__(self):
        return "info=%s, fatal=%s for %s on %s" % (self.info_count, self.fatal_count, self.category, self.date)

class ComputedTrend(models.Model):
    for_date = models.DateField()
    days_back = models.IntegerField()
    info_trend = models.FloatField()
    fatal_trend = models.FloatField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    keyed_tag = models.ForeignKey("EventTagKeyed", null=True, blank=True, on_delete=models.SET_NULL)

    class Meta:
        # potentially a very large index?
        unique_together = ['keyed_tag', 'category', 'for_date', 'days_back']

    def __str__(self):
        return "info=%s, fatal=%s for %s as of %s going back %d" % (self.info_trend, self.fatal_trend, self.category, self.for_date, self.days_back)

class EventGroup(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    group_id = models.IntegerField()
    categories = models.ManyToManyField(Category, through='AssignedCategory')

    class Meta:
        unique_together = ['project', 'group_id']

    def __str__(self):
        return f"{self.group_id} (events: {self.event_count()})"

    def event_info_count(self):
        return self.event_set.filter(tags__value='info', tags__event_tag__key='level').count()

    def event_fatal_count(self):
        return self.event_set.exclude(tags__value='info', tags__event_tag__key='level').count()

    def event_count(self):
        return self.event_set.all().count()

class EventTag(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    key = models.CharField(max_length=255)

    class Meta:
        unique_together = ['project', 'key']

    def __str__(self):
        return "%s: %s" % (self.project.name, self.key)

class EventTagKeyed(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    event_tag = models.ForeignKey(EventTag, on_delete=models.CASCADE)
    value = models.CharField(max_length=255)

    class Meta:
        # running a data import from sentry somehow produced a constraint violation that wasn't caught during an insert.
        # had to find it manually and resolve it (by deleting bad records).
        # >>> r = EventTagKeyed.objects.raw('select * from crashes_eventtagkeyed group by event_tag_id, value having count(*) > 1')
        # >>> r[0]
        # <EventTagKeyed: device = Joy 1+>
        # >>> r[1]
        # <EventTagKeyed: device = LG-V400>
        # >>> r[2]
        # Traceback (most recent call last):
        #   File "<console>", line 1, in <module>
        #   File "/Users/grishakruglov/Code/sentry-analyzer/venv/lib/python3.9/site-packages/django/db/models/query.py", line 1526, in __getitem__
        #     return list(self)[k]
        # IndexError: list index out of range
        # >>> r[0].delete()
        # >>> r[1].delete()
        unique_together = ['project', 'event_tag', 'value']

    def __str__(self):
        return f"{self.event_tag.key} = {self.value}"

class ProcessEventTag(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    event_tag = models.ForeignKey(EventTag, on_delete=models.CASCADE)

    def __str__(self):
        return "Process %s: %s" % (self.project, self.event_tag)

class Event(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    group = models.ForeignKey(EventGroup, on_delete=models.CASCADE)
    event_id = models.CharField(max_length=255)
    sentry_id = models.IntegerField()
    event_received = models.DateTimeField()
    event_created = models.DateTimeField()
    created = models.DateTimeField(auto_now_add=True)
    message = models.CharField(max_length=2048, null=True, blank=True)
    tags = models.ManyToManyField(EventTagKeyed)
    info = models.BooleanField(null=True, blank=True)

    class Meta:
        unique_together = ['project', 'sentry_id']
        ordering = ['-event_created',]

    def is_info(self):
        if self.info is None:
            self.info = self.tags.filter(value='info', event_tag__key='level').count() > 0
            return self.info
        else:
            return self.info

    def __str__(self):
        return f"{self.sentry_id} : {self.message}"

class AssignedCategory(models.Model):
    group = models.ForeignKey(EventGroup, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    confidence = models.FloatField(default=1.0)

    class Meta:
        unique_together = ['group', 'category']

class Stacktrace(models.Model):
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    stacktrace = models.TextField()
    processed = models.BooleanField(default=False)

    def __str__(self):
        return f"Stacktrace for {self.event.message}"

class ProjectEndpointCache(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    json = models.TextField()
    sample_date = models.DateTimeField()

crashes/views.py
from django.shortcuts import render
from django.core.cache import cache
from .models import Category, CategoryCount, Organization, Stacktrace, Event, Project, ComputedTrend

import datetime

def org(request, org_slug):
    org = Organization.objects.get(slug=org_slug)
    return render(request, 'crashes/org.html', {
        'org': org
    })

def project(request, org_slug, project_slug):
    project = Project.objects.get(slug=project_slug, org__slug=org_slug)
    stacktraces_all = Stacktrace.objects.filter(event__project=project).count()
    stacktraces_processed = Stacktrace.objects.filter(event__project=project, processed=True).count()

    processed_progress = 0
    latest_event = None
    oldest_event = None
    if stacktraces_all > 0:
        processed_progress = (stacktraces_processed / stacktraces_all) * 100
        latest_event = Event.objects.filter(project=project).order_by('-event_created').values('event_created')[0]
        oldest_event = Event.objects.filter(project=project).order_by('event_created').values('event_created')[0]

    today = datetime.date.today() - datetime.timedelta(days=1)
    cutoff_date = today - datetime.timedelta(days=89)
    date_list = [(today - datetime.timedelta(days=x)) for x in range(90)]
    packages = []
    # if data for 'today' is missing, trend selection won't work.
    # what this should do instead:
    # - lookup latest date for which we have calculated trends
    # - get trends for that date
    # - indicate in the output how many days old is the data, so that the UI can adjust
    for category in Category.objects.filter(project=project).values('id', 'name'):
        package = {
            "name": category['name'],
            "dates": {d.isoformat(): {'info': -1, 'fatal': -1} for d in date_list},
            "trends": {d: {'info': 0, 'fatal': 0} for d in range(len(date_list))}
        }
        for cc in CategoryCount.objects.filter(keyed_tag=None, category__id=category['id'], date__lte=today, date__gte=cutoff_date).values('date', 'info_count', 'fatal_count'):
            package['dates'][cc['date'].isoformat()]['info'] = cc['info_count']
            package['dates'][cc['date'].isoformat()]['fatal'] = cc['fatal_count']

        for ct in ComputedTrend.objects.filter(keyed_tag=None, category__id=category['id'], for_date=today, days_back__lt=len(date_list)).values('days_back', 'info_trend', 'fatal_trend'):
            package['trends'][ct['days_back']]['info'] = ct['info_trend']
            package['trends'][ct['days_back']]['fatal'] = ct['fatal_trend']

        packages.append(package)

    return render(request, 'crashes/packages.html', {
        'project': project,
        'packages': packages,
        'stacktraces_processed': stacktraces_processed,
        'stacktraces_all': stacktraces_all,
        'processed_progress': processed_progress,
        'latest_event': latest_event,
        'oldest_event': oldest_event
    })

def package(request, org_slug, project_slug, package_name):
    today = datetime.datetime.today()
    cutoff_date = today - datetime.timedelta(days=29)
    date_list = [(today - datetime.timedelta(days=x)).date() for x in range(30)]
    p = Category.objects.get(project__org__slug=org_slug, project__slug=project_slug, name=package_name)
    package = {
        "name": p.name,
        "groups": []
    }
    for group in p.eventgroup_set.all():
        g = {
            "id": group.id,
            "event_count": group.event_count(),
            "url": "https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/%s" % group.group_id,
            "events": [],
            "dates": {d.isoformat(): {'info': 0, 'fatal': 0} for d in date_list}
        }
        for event in group.event_set.filter(event_created__gte=cutoff_date):
            s = event.stacktrace_set.all().first()
            if s:
                s = s.stacktrace
            else:
                s = ""
            g['events'].append({
                "id": event.id,
                "is_info": event.is_info(),
                "url": "https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/%s/events/%s/" % (event.group.group_id, event.sentry_id),
                "message": event.message,
                "stacktrace": s
            })
            if event.is_info():
                g['dates'][event.event_created.date().isoformat()]['info'] += 1
            else:
                g['dates'][event.event_created.date().isoformat()]['fatal'] += 1

        package['groups'].append(g)

    return render(request, 'crashes/package.html', {
        'project': p.project,
        'package': package
    })

crashes/templates/crashes/base.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>{% block title %}{% endblock %}</title>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
        integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    {% block css %}{% endblock %}
</head>

<body>
    <!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Sentry Analyzer</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="https://github.com/grigoryk/sentry-analyzer/">Source Code</a></li>
                </ul>
            </div>
            <!--/.nav-collapse -->
        </div>
    </nav>

    <div class="container">
        {% block content %}{% endblock %}
    </div>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://code.jquery.com/jquery-1.12.4.min.js"
        integrity="sha384-nvAa0+6Qg9clwYCGGPpDQLVpLNn0fRaROjHqs13t4Ggj3Ez50XnGQqc/r8MhnRDZ"
        crossorigin="anonymous"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
        integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd"
        crossorigin="anonymous"></script>

    <script src="https://knockoutjs.com/downloads/knockout-3.5.1.js"></script>

    <script>
        const cyrb53 = function(str, seed = 0) {
            let h1 = 0xdeadbeef ^ seed, h2 = 0x41c6ce57 ^ seed;
            for (let i = 0, ch; i < str.length; i++) {
                ch = str.charCodeAt(i);
                h1 = Math.imul(h1 ^ ch, 2654435761);
                h2 = Math.imul(h2 ^ ch, 1597334677);
            }
            h1 = Math.imul(h1 ^ (h1>>>16), 2246822507) ^ Math.imul(h2 ^ (h2>>>13), 3266489909);
            h2 = Math.imul(h2 ^ (h2>>>16), 2246822507) ^ Math.imul(h1 ^ (h1>>>13), 3266489909);
            return 4294967296 * (2097151 & h2) + (h1>>>0);
        };

        // from https://medium.com/@sahirnambiar/linear-least-squares-a-javascript-implementation-and-a-definitional-question-e3fba55a6d4b
        function findLineByLeastSquares(values_x, values_y) {
            var x_sum = 0;
            var y_sum = 0;
            var xy_sum = 0;
            var xx_sum = 0;
            var count = 0;

            /*
            * The above is just for quick access, makes the program faster
            */
            var x = 0;
            var y = 0;
            var values_length = values_x.length;

            if (values_length != values_y.length) {
                throw new Error('The parameters values_x and values_y need to have same size!');
            }

            /*
            * Above and below cover edge cases
            */
            if (values_length === 0) {
                return [ [], [] ];
            }

            /*
            * Calculate the sum for each of the parts necessary.
            */
            for (let i = 0; i< values_length; i++) {
                x = values_x[i];
                y = values_y[i];
                x_sum+= x;
                y_sum+= y;
                xx_sum += x*x;
                xy_sum += x*y;
                count++;
            }

            /*
            * Calculate m and b for the line equation:
            * y = x * m + b
            */
            var m = (count*xy_sum - x_sum*y_sum) / (count*xx_sum - x_sum*x_sum);
            var b = (y_sum/count) - (m*x_sum)/count;

            /*
            * We then return the x and y data points according to our fit
            */
            var result_values_x = [];
            var result_values_y = [];

            for (let i = 0; i < values_length; i++) {
                x = values_x[i];
                y = x * m + b;
                result_values_x.push(x);
                result_values_y.push(y);
            }

            return [result_values_x, result_values_y];
        }

        // from http://www.knockmeout.net/2011/06/fun-with-highlighting-in-knockoutjs.html
        ko.bindingHandlers.highlightedText = {
            update: function(element, valueAccessor) {
                var options = valueAccessor();
                var value = ko.utils.unwrapObservable(options.text);
                var search = ko.utils.unwrapObservable(options.highlight);
                var css = ko.utils.unwrapObservable(options.css);
                if (options.sanitize) {
                    value = $('<div/>').text(value).html(); //could do this or something similar to escape HTML before replacement, if there is a risk of HTML injection in this value
                }
                var replacement = '<span class="' + css + '">' + search + '</span>';
                element.innerHTML = value.replace(new RegExp(search, 'g'), replacement);
            }
        };
    </script>
    {% block scripts %}{% endblock %}
</body>

</html>

crashes/templates/crashes/org.html
{% extends "crashes/base.html" %}

{% block title %}Sentry analyzer: {{ org.name }}{% endblock %}

{% block content %}
    <div class="jumbotron">
        <div class="row">
            <div class="col-md-8"><h2>{{ org.name }} - Sentry Analyzer</h2></div>
        </div>
        <div class="row" style="padding-top: 20px;">
            <div class="col-md-12">
                {% for project in org.project_set.all %}
                    <h2><a href="{% url 'project' org.slug project.slug %}">{{ project.name }}</a></h2>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

crashes/templates/crashes/package.html
{% extends "crashes/base.html" %}

{% block title %}Sentry analyzer: package {{ package.name}}{% endblock %}

{% block css %}
    <style>
        div.chart {
            border-bottom: solid 1px rgb(106, 106, 106);
        }

        div.bar {
            width: 5px;
            display: inline-block;
            background-color: #686666;
        }

        .highlight {
            background-color: rgb(38, 38, 38);
            color: rgb(235, 235, 235);
        }
    </style>
{% endblock %}

{% block content %}
<div class="jumbotron">
    <div class="row">
        <div class="col-md-12">
            <h2><a href="{% url 'project' project.org.slug project.slug %}">&larr;</a>{{ package.name }}</h2>
        </div>
    </div>

    <div class="row">
        <div class="col-md-4">
            <div class="form-inline">
                <input data-bind="textInput: search" type="text" class="form-control" id="packageSearch" placeholder="Search stacktrace, etc...">
                <label for="timeRange">Past <span data-bind="text: timeRange"></span> <span data-bind="text: timeRange() == 1 ? 'day' : 'days'"></span></label>
                <input id="timeRange" type="range" min="1" max="90" data-bind="value: timeRange, valueUpdate: 'input'">
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-4">
            <p>Event filter: <select data-bind="options: ['info', 'fatal'], value: eventFilter"></select></p>
            <p>Sort by: <select data-bind="options: ['trend', 'total'], value: sortBy"></select><select data-bind="options: ['desc', 'asc'], value: sortDirection"></select></p>
            <div class="checkbox" data-bind="if: oom_count() > 0">
                <label>
                    <input type="checkbox" id="includeOOM" data-bind="checked: includeOOM"> Include OOM (<span data-bind="text: oom_count"></span>)
                </label>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12" data-bind="foreach: filtered_groups">
            <div data-bind="if: (is_info ? info_count() : fatal_count()) > 0">
                <h2>
                    <span class="label" data-bind="css: {'label-warning': trend() > 0, 'label-success': trend() < 0, 'label-default': trend() == 0 }">
                        <span class="glyphicon" data-bind="css: {'glyphicon-arrow-up': trend() > 0, 'glyphicon-arrow-down': trend() < 0, 'glyphicon-option-horizontal': trend() == 0}"></span>
                        <span data-bind="text: trend, visible: trend() != 0"></span>
                    </span>
                    <span data-bind="text: is_info ? 'info' : 'fatal', css: {'label-info' : is_info, 'label-danger': !is_info}" class="label"></span>
                    <a data-bind="attr: { href: url }">Group of <span data-bind="text: is_info ? info_count() : fatal_count()"></span> events</a>
                </h2>

                <div class="chart" data-bind="style: { width: raw().length * 5 * 2 }, foreach: normalized_raw">
                    <div class="bar" data-bind="style: { height: $data }"></div>
                </div>

                <!-- ko if: active_event -->
                <div class="row">
                    <nav class="col-md-4">
                        <ul class="pager">
                            <li><a data-bind="visible: active_event_index() > 0, click: previousEvent" href="#">&larr;</a></li>
                            <li><span data-bind="text: 'Unique stacktrace #' + (active_event_index() + 1) + ':'"></span></li>
                            <li><a data-bind="visible: active_event_index() < (unique_events.length - 1), click: nextEvent" href="#">&rarr;</a></li>
                        </ul>
                    </nav>
                </div>
                <div data-bind="using: active_event">
                    <a data-bind="attr: { href: url }">
                        <strong data-bind="text: message"></strong>
                    </a>
                    <div class="stacktrace" data-bind="foreach: stacktrace_lines">
                        <div data-bind="highlightedText: { text: $data, highlight: search, css: 'highlight' }"></div>
                    </div>
                </div>
            <!-- /ko -->
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script type="text/javascript">
    var globalTimeRange;
    var globalOlsCache = {};

    function Event(data) {
        var self = this;
        self.id = data.id;
        self.url = data.url;
        self.is_info = data.is_info;
        self.message = data.message;
        self.stacktrace = data.stacktrace;
        self.stacktrace_lines = self.stacktrace.split('\n');
        self.label = ko.computed(function() {
            return "Event #" + self.id;
        })
    }

    function Group(data) {
        var self = this;
        self.id = data.id;
        self.url = data.url;
        self.dates = ko.observableArray(data.dates);
        self.limitedDates = ko.computed(() => {
            var now = Date.now();
            return ko.utils.arrayFilter(self.dates(), (date) => {
                var d = Date.parse(date.date);
                var delta = Math.floor((now - d) / (1000 * 60 * 60 * 24));
                var timeRangeLimit = globalTimeRange();
                return delta <= timeRangeLimit;
            });
        });
        self.info_count = ko.computed(function() {
            var dates = self.limitedDates();
            return self.limitedDates().reduce((sum, val) => sum + val.info, 0);
        });
        self.fatal_count = ko.computed(function() {
            var dates = self.limitedDates();
            return self.limitedDates().reduce((sum, val) => sum + val.fatal, 0);
        });

        self.event_count = data.event_count;
        self.events = $.map(data.events, function(e) { return new Event(e) });
        self.unique_events = (() => {
            var stacktrace_set = {};
            return ko.utils.arrayFilter(self.events, (e) => {
                var withoutLineNumbers = $.map(e.stacktrace.split('\n'), (l) => {
                    return l.split('@')[0];
                });
                var hash = cyrb53(withoutLineNumbers.join(''));
                if (stacktrace_set.hasOwnProperty(hash)) {
                    return false;
                }
                stacktrace_set[hash] = true;
                return true;
            })
        })();
        self.active_event_index = ko.observable(0);
        self.active_event = ko.computed(function() {
            return self.unique_events[self.active_event_index()];
        });
        if (self.events.length > 0) {
            self.is_info = self.events[0].is_info;
            self.is_oom = self.events[0].message.startsWith('OutOfMemoryError') || self.events[0].message.startsWith('Failed to allocate');
            self.search_target = self.events[0].message + self.events[0].stacktrace;
        } else {
            self.is_info = false;
            self.is_oom = false;
            self.search_target = "";
        }
        self.trend = ko.computed(function() {
            if (globalTimeRange() == 1) {
                return 0;
            } else {
                return trendOLS(self.limitedDates(), self.is_info ? 'info' : 'fatal');
            }
        });
        self.raw = ko.computed(() => {
            var raw = rawValues(self.limitedDates(), self.is_info ? 'info' : 'fatal');
            return raw.slice(0, raw.length - 1);
        });
        self.normalized_raw = ko.computed(() => {
            var raw = self.raw();
            var max = Math.max(...raw);
            return $.map(raw, (r) => 50 * r / max);
        });
        function rawValues(dates, key) {
            var dx = Array.from(dates).reverse();
            return $.map(dx, (d) => d[key]);
        }
        function trendOLS(dates, key) {
            var dates_hash = key + cyrb53(JSON.stringify(dates));
            if (globalOlsCache.hasOwnProperty(dates_hash)) {
                return globalOlsCache[dates_hash];
            }

            var xset = [...Array(dates.length + 1).keys()].slice(1);
            var yset = rawValues(dates, key);

            // exclude last day (it's usually incomplete).
            var xset_sliced = xset.slice(0, xset.length - 1);
            var yset_sliced = yset.slice(0, yset.length - 1);
            var ols = findLineByLeastSquares(xset_sliced, yset_sliced);
            var diffs = [];
            ols[1].forEach((current, i) => {
                // -2 to exclude last day
                if (i == (dates.length - 2)) {
                    return;
                }

                var next = ols[1][i + 1];
                diffs.push(next - current);
            });
            var res = Math.round(1000 * diffs.reduce((sum, v) => sum + v, 0) / diffs.length) / 1000;
            globalOlsCache[dates_hash] = res;
            return res;
        }
    }

    function VM(groups) {
        var self = this;
        self.eventFilter = ko.observable('fatal');
        self.sortBy = ko.observable('trend');
        self.sortDirection = ko.observable('desc');
        self.includeOOM = ko.observable(false);

        self.timeRange = ko.observable(7);
        // well, that's a hack :/ not sure how else to access this from Pacakge.
        globalTimeRange = self.timeRange;
        self.search = ko.observable("");

        self.groups = ko.observableArray(
            $.map(groups, function(g) { return new Group(g) })
        );

        self.oom_count = ko.computed(() => {
            return self.groups().reduce((sum, val) => {
                if (val.is_oom) {
                    return sum + 1;
                } else {
                    return sum;
                }
            }, 0);
        });

        function compare(left, right, direction) {
            if (direction == 'desc') {
                return left < right;
            } else {
                return left > right;
            }
        }
        self.sorted_groups = ko.computed(function() {
            return self.groups.sorted(function (left, right) {
                if (self.sortBy() == 'trend') {
                    return compare(left.trend(), right.trend(), self.sortDirection());
                } // else 'total'

                if (self.eventFilter() == 'info') {
                    return compare(left.info_count(), right.info_count(), self.sortDirection());
                } else {
                    return compare(left.fatal_count(), right.fatal_count(), self.sortDirection());
                }
            })
        });
        self.filtered_groups = ko.computed(function() {
            return ko.utils.arrayFilter(self.sorted_groups(), function(group) {
                var include = true;
                if (!self.includeOOM()) {
                    include = include && !group.is_oom;
                }
                if (self.eventFilter() == 'fatal') {
                    include = include && !group.is_info;
                } else {
                    include = include && group.is_info;
                }
                if (self.search()) {
                    include = include && group.search_target.includes(self.search());
                }
                return include;
            });
        });
        self.previousEvent = function(group) {
            if (group.active_event_index() > 0) {
                group.active_event_index(group.active_event_index() - 1);
            }
        };
        self.nextEvent = function(group) {
            if (group.active_event_index() < group.unique_events.length) {
                group.active_event_index(group.active_event_index() + 1);
            }
        };
    }
    ko.applyBindings(VM(
        [
            {% for group in package.groups %}
            { id: '{{ group.id }}', event_count: {{ group.event_count }}, url: '{{ group.url }}',

                dates: [
                {% for date, counts in group.dates.items %}
                    { date: '{{ date }}', info: {{ counts.info }}, fatal : {{ counts.fatal }} },
                {% endfor %}
                ],

                events:
                [
                {% for event in group.events %}
                    { id: '{{ event.id }}', is_info: {{ event.is_info|yesno:"true,false" }}, url: '{{ event.url }}', message: '{{ event.message|escapejs }}', stacktrace: '{{ event.stacktrace|escapejs }}'},
                {% endfor %}
                ]
            },
            {% endfor %}
        ]
    ));
</script>
{% endblock %}